server:
  port: ${APP_PORT:8080}
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: INFO
spring:
  application:
    name: iLog-backend
  datasource:
    url: jdbc:postgresql://${ILOG_DATABASE_HOST:localhost}:${ILOG_DATABASE_PORT:5432}/${ILOG_DATABASE:iLog}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_ID}
            client-secret: ${OKTA_SECRET}
            scope: openid, email, profile
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: openid, email, profile
          facebook:
            client-id: ${FACEBOOK_ID}
            client-secret: ${FACEBOOK_SECRET}
            scope: public_profile, email
        provider:
          okta:
            issuer-uri: https://dev-46446375.okta.com/oauth2/default